### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by Hokua** [musictheory/oj#55]
I wonder if there is any plan to implement Objective-C Categories?

**Comment by IngwiePhoenix** [comment]
Just curios, but would you mind sharing a pseudo-example how that would possibly look/work in OJ and what could be done with it?

**Comment by Hokua** [comment]
Categories are a core feature of objective-c, would be nice to use them with the oj compiler. Right now you get an compile error. What should happen is the methods get added to an existing class (if the class doesnt existing, you get a runtime exception)

**Comment by iccir** [comment]
This should be doable, syntax would be similar to Obj-C:

    @implementation Foo (CategoryName)
    @end

Which would have an AST node similar to:

   { type: Syntax.OJClassImplementation, id: "Foo", category: "CategoryName", body: ... }

Likely `handleClassImplementation` in the generator would be modified to call some kind of `_registerCategory` function in this case rather than `_registerClass` at runtime.

**Comment by iccir** [comment]
6072f88 adds the ability to define categories which add methods, similar to objc 1.

The following are unsupported:
- Class extensions
- `@property` and `@dynamic` in a category implementation

Like Obj-C, defining a method that already exists is undefined behavior.
